projects.yaml

add mkdocs-typer

---

.github/workflows/ci.yml
check_projects.py
projects.yaml

Closes #44 
Add information about MkDocs plugin and extension names
In CI, check they are specified correctly and can actually be used under those names.
This information is not exposed in the readme.
**Checklist:**

Add information about MkDocs plugin and extension names

---

.github/workflows/ci.yml
.github/workflows/update-best-of-list.yml

Chore dependency upgrade

---

projects.yaml

This add my plugin to stop the sitemap from being generated.
**Checklist:**

Add no-sitemap plugin

---

projects.yaml

Plugin for minification using [minify-html](https://github.com/wilsonzlin/minify-html), an extremely fast HTML + JS + CSS minifier.
**Checklist:**

Add project: mkdocs-minify-html-plugin

---

projects.yaml

Add mkdocs-site-urls: A MkDocs plugin that adds support for site-relative `site:` URLs. 
**Checklist:**

Add project: mkdocs-site-urls

---

projects.yaml

A simple theme for MkDocs, using the w3.css framework and configurable color schemes.
**Checklist:**

Add project: mkdocs-risonia-theme

---

projects.yaml

An interactive family tree visualization that imports genealogy data from Gramps.
**Checklist:**

Add project: mkdocs-familytree-example

---

projects.yaml

Add mkdocs-ezglossary-plugin

---

projects.yaml

Add pymdownx block extensions

---

projects.yaml

Added a PyPi link to `mkdocs-render-swagger-plugin`
**Checklist:**

Added pypi for mkdocs-render-swagger-plugin

---

projects.yaml

* Closes https://github.com/pawamoy/mkdocs-gallery/issues/4
@pawamoy created issues on respective repositories, we can re-add the themes in case there is any response.

Delete unmaintained themes

---

projects.yaml

Add plugins: mkdocs-zip-folders, mkdocs-typedoc, resize-images
**Checklist:**

Add plugins: mkdocs-zip-folders, mkdocs-typedoc, resize-images

---

check_projects.py
projects.yaml

The official package index does it

Normalize pypi_ids to use dashes

---

projects.yaml

Add plugins and deps for mkdocs-material

---

projects.yaml

Adds an entry for the extract-listings plugin, which extracts all listings (code blocks) and collects them on a single page. It can also create a search page for only listings, so I put it in the search category.
**Checklist:**

Add project: extract-listings

---

projects.yaml

This PR adds [my plugin](https://github.com/landmaj/mkdocs-d2-plugin/) for rendering [D2](https://d2lang.com/) diagrams in MkDocs.
**Checklist:**

Add project: mkdocs-d2-plugin

---

projects.yaml

https://github.com/WSOFT-Project/lantana/issues/48
**Checklist:**

Re-add Lantana theme (fixed upstream)

---

projects.yaml

This reverts commit a89e319947072fbdbfb4103390f35ab7e4c516c3.
**Checklist:**

Revert "Add mkdocs-basic-theme"

---

projects.yaml

Add mkdocs plugin image-formatter-plugin. The plugin allows the user to define image size categories and use them as tags in the documentation. The images annotated with tags will be resized to the size specified in the configuration file.
**Checklist:**

Add plugin: image-formatter-plugin

---

projects.yaml

New plugin `mkdocs-pagetree-plugin` added: Insertion of an expandable/collapsible page tree of all pages via the placeholder `{{ pagetree }}`.
* Repository: https://github.com/tombreit/mkdocs-pagetree-plugin
* PyPI: https://pypi.org/project/mkdocs-pagetree-plugin/
* Demo: https://tombreit.github.io/mkdocs-pagetree-plugin/
**Checklist:**

Add project: mkdocs-pagetree-plugin

---

projects.yaml

Add project: mkdocs-git-latest-changes-plugin
MkDocs plugin that allows you to display a list of recently modified pages from the Git log
- [Demo](https://tombreit.github.io/mkdocs-git-latest-changes-plugin/)
- [Repository](https://github.com/tombreit/mkdocs-git-latest-changes-plugin)
- [PyPI package](https://pypi.org/project/mkdocs-git-latest-changes-plugin/)
**Checklist:**

Add project: mkdocs-git-latest-changes-plugin

---

projects.yaml

Adding [mkdocs_licenseinfo](https://github.com/djpugh/mkdocs_licenseinfo) - Automatically generate license information for dependencies using ``licensecheck``
* Example: https://djpugh.github.io/mkdocs_licenseinfo/latest/developing/sbom/
**Checklist:**

Add project: mkdocs_licenseinfo

---

projects.yaml

Following https://github.com/pawamoy/markdown-exec/issues/28
**Checklist:**

Markdown exec extra deps

---

projects.yaml

Added the `inline-svg` plugin, using the [`mkdocs-plugin-inline-svg-mod`](https://pypi.org/project/mkdocs-plugin-inline-svg-mod) package. This is the actively maintained version, having forked from [Nicholas Dupoint's](https://gitlab.com/nicolas.dupont/mkdocs-plugin-inline-svg/-/tree/master) and [Craig Robert's](https://gitlab.com/craig0990/mkdocs-plugin-inline-svg) versions
**Checklist:**

Add inline-svg plugin

---

projects.yaml

Added ldeluigi/markdown-docs gh action to the list
**Checklist:**

Add markdown-docs action project to the list. Closes #181

---

projects.yaml

Plugin for Material for MkDocs to draw an interactive graph like Obsidian. The graph inside the sidebar is just available for non-mobile website. The modal view via the button next to the search bar shall work on all devices.
Refer [Github Pages](https://daxcore.github.io/mkdocs-obsidian-interactive-graph-plugin/) for a demonstration of the interactive graph in Material for MkDocs.
**Checklist:**

Add Interactive Graph Plugin

---

projects.yaml

`mkdocs-version-annotations` (mkdocs plugin) has been converted to the more general-purpose `markdown-version-annotations` (Markdown extension) with some feature enhancements as well.
**Checklist:**

Replace mkdocs-version-annotations with markdown-version-annotations

---

projects.yaml

Added the available handlers of mkdocstrings. Mostly want to see how that looks in the generated README :thinking: 
They're not really MkDocs plugins, not Markdown extensions, but I do believe showing them is helpful, as users might search for "crystal" or "typescript" to see if there's anything related to the language used in the project they want to document with MkDocs.
**Checklist:**

Add mkdocstrings handlers

---

projects.yaml

Add the great [svgbob extension for Python Markdown](https://github.com/mbarkhau/markdown-svgbob) which renders diagrams using [svgbob](https://github.com/ivanceras/svgbob).
You can try it out using the [Svgbob Editor](https://ivanceras.github.io/svgbob-editor/) or the [AsciiGrid Editor](https://asciigrid.litprog.dev/).
**Checklist:**

Add project: markdown-svgbob

---

projects.yaml

A plugin for showing the state and labels of issues (GitHub or GitLab) in mkdocs generated docs. 
Part-of: https://github.com/mkdocs/catalog/issues/235.
**Checklist:**

Add project: mkdocs-issues-plugin

---

projects.yaml

mkdocs-task-collector is a MkDocs plugin designed to streamline your documentation workflow by automatically scanning your Markdown files for specific annotations like TODO, NOTE, and PLACEHOLDER, and organizing them into structured list as a page of your documentation with no extra configurations needed.
**Checklist:**

Add project: mkdocs-task-collector

---

projects.yaml

Add project: mkdocs-asciinema-player

---

projects.yaml

mkdocs-pipeline-visualizer, it generates documentation from Tetkton pipelines and tasks.
**Checklist:**

Add project: mkdocs-pipeline-visualizer

---

projects.yaml

feat: mkdocs-breadcrumbs-plugin - Add

---

projects.yaml

I added the mkdocs-panzoom-plugin which allows panning and zooming on mermaid diagrams and images.
**Checklist:**

add mkdocs-panzoom-plugin

---

projects.yaml

mkdocs_puml is a plugin that adds a support for inline PlantUML diagrams. 
**Checklist:**

Add project: mkdocs_puml

---

projects.yaml

Add project: mkdocs-curriculum-vitae

---

projects.yaml

mkdocs-vercel-pw-plugin: Allows you to password protect your site if it is deployed by Vercel.
**Checklist:**

Add project: mkdocs-vercel-pw-plugin

---

projects.yaml

Add licenses to Windmill and Cinder

---

projects.yaml

Add `mkdocs-backlinks-section-plugin`, which adds a backlinks section that lists every page linking to the current page.
**Checklist:**

Add project: mkdocs-backlinks-section-plugin

---

projects.yaml

I add oEmbedPy project that is client library of oEmbed API.
This project includes MkDocs plugin.
**Checklist:**

Add project: oEmbedPy

---

projects.yaml

cc @pawamoy ... it's on PyPI now and the name is correct.  thanks!

uncomment mkdocs-api-autonav

---

projects.yaml

- Cleaned up dead code 
- Moved ansible-mkdocs to the correct category section
Added [mkdocs-azure-pipelines](https://github.com/Wesztman/mkdocs-azure-pipelines)
**Checklist:**

Add project: Added mkdocs-azure-pipelines (also did some cleaning)

---

projects.yaml

Closes #316 
Add Add mkdocs-mcp
**Checklist:**

Add mkdocs-mcp

---

projects.yaml

Add project: mkdocs-shadcn

---

projects.yaml

Hi,
mkdocs-navsorted-plugin — Use numeric prefixes for your documentation files/directories names to drive navigation items sort order.
https://mkdocs-navsorted-plugin.readthedocs.io/en/latest/
**Checklist:**

Add project: mkdocs-navsorted-plugin

---

projects.yaml

Hi,
Easy way to configure the plugin.
**Checklist:**

Update project: mkdocs-apidescribed-plugin

---

projects.yaml

Add mkdocs-matplotlib to catalog
Add mkdocs-matplotlib to catalog.
**Checklist:**

Add mkdocs-matplotlib to catalog

---

projects.yaml

https://github.com/NickCrews/mkdocs-jupyterlite
A MkDocs plugin for embedding interactive jupyter notebooks in your docs with jupyterlite.
**Checklist:**

Add https://github.com/NickCrews/mkdocs-jupyterlite

---

projects.yaml

MkDocs Copy to LLM
A MkDocs plugin that adds "Copy to LLM" buttons to your documentation, making it easy to copy code blocks and entire pages in formats optimized for Large Language Models (LLMs).
**Checklist:**

Add mkdocs-copy-to-llm

---

projects.yaml

One line of code to display a list of recently updated documents
**Checklist:**

Add project: mkdocs-recently-updated-docs
